Weekly Sales Tally 2023 Query:

let
    Source = Excel.Workbook(File.Contents("C:\Users\Thomas\Downloads\Summer-2023-Product-Analyst-Intern-Projects-main\Power BI\Weekly Sales Dashboard\Sales Tally Numbers 2023.xlsx"), null, true),
    #"Weekly Sales Tally 2023_Sheet" = Source{[Item="Weekly Sales Tally 2023",Kind="Sheet"]}[Data],
    #"Changed Type" = Table.TransformColumnTypes(#"Weekly Sales Tally 2023_Sheet",{{"Column1", type text}, {"Column2", type any}, {"Column3", type any}, {"Column4", type any}, {"Column5", type any}, {"Column6", type any}, {"Column7", type any}, {"Column8", type any}, {"Column9", type any}, {"Column10", type any}, {"Column11", type any}, {"Column12", type any}, {"Column13", type any}, {"Column14", type any}, {"Column15", type any}, {"Column16", type any}, {"Column17", type any}, {"Column18", type any}, {"Column19", type any}, {"Column20", type any}, {"Column21", type any}, {"Column22", type any}, {"Column23", type any}, {"Column24", type any}, {"Column25", type any}, {"Column26", type any}, {"Column27", type any}, {"Column28", type any}, {"Column29", type any}, {"Column30", type any}, {"Column31", type any}, {"Column32", type any}, {"Column33", type any}, {"Column34", type any}, {"Column35", type any}, {"Column36", type any}, {"Column37", type any}, {"Column38", type any}, {"Column39", type any}, {"Column40", type date}, {"Column41", type number}, {"Column42", type any}, {"Column43", type any}, {"Column44", type any}, {"Column45", type any}, {"Column46", type any}, {"Column47", type any}, {"Column48", type any}, {"Column49", type any}, {"Column50", type any}, {"Column51", type any}, {"Column52", type any}, {"Column53", type any}, {"Column54", type any}, {"Column55", type any}, {"Column56", type any}, {"Column57", type any}, {"Column58", type any}, {"Column59", type any}, {"Column60", type any}, {"Column61", type any}, {"Column62", type any}, {"Column63", type any}, {"Column64", type any}, {"Column65", type any}, {"Column66", type any}}),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column8"}),
    #"Transposed Table" = Table.Transpose(#"Removed Columns"),
    #"Promoted Headers" = Table.PromoteHeaders(#"Transposed Table", [PromoteAllScalars=true]),
    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}}),
    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Changed Type1", {"Date"}),
    #"Filtered Rows" = Table.SelectRows(#"Removed Errors", each ([Date] <> null)),
    #"Changed Type2" = Table.TransformColumnTypes(#"Filtered Rows",{{"# of Orders in Production (Expected to Ship)", type number}, {"# of Paid orders MAY not make PRODUCTION", type number}, {"# of Paid Orders WILL NOT make PRODUCTION ", type number}}),
    #"Added Custom" = Table.AddColumn(#"Changed Type2", "Orders MAY NOT divide by Orders in Production", each [#"# of Paid Orders WILL NOT make PRODUCTION "] / [#"# of Orders in Production (Expected to Ship)"]),
    #"Renamed Columns" = Table.RenameColumns(#"Added Custom",{{"# of Orders in Production (Expected to Ship)", "Expected to Ship"}, {"# of Paid orders MAY not make PRODUCTION", "May Not Make Production"}, {"# of Paid Orders WILL NOT make PRODUCTION ", "Will Not Make Production"}, {"# of orders waiting for payment", "Waiting for Payment"}}),
    #"Changed Type3" = Table.TransformColumnTypes(#"Renamed Columns",{{"Waiting for Payment", type number}, {"Total $ Shipped", type number}, {"Total $ in Production", type number}, {"$ of Paid orders MAY not make PRODUCTION", type number}, {"$ of Paid orders WILL NOT make PRODUCTION", type number}, {"Total $ Waiting for Payment", type number}, {"Projected Net OUT Month", type number}, {"Previous Month's Totals", type number}, {"Previous Year's Monthly Totals", type number}, {"Orders In", type number}, {"Zeal Orders", type number}}),
    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type3",{{"$ of Paid orders WILL NOT make PRODUCTION", "$ Will Not Make Production"}, {"Projected Net OUT Month", "Projected OUT Revenue"}, {"Total $ Shipped", "Total Revenue Shipped"}})
in
    #"Renamed Columns1"