Monthly Report 1 Query:

let
    Source = Excel.Workbook(File.Contents("C:\Users\Thomas\Downloads\Summer-2023-Product-Analyst-Intern-Projects-main\Power BI\Monthly Sales Dashboard\Monthly Sales Report Dashboard.xlsx"), null, true),
    #"Monthly Report 1_Sheet" = Source{[Item="Monthly Report 1",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(#"Monthly Report 1_Sheet", [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Month", type text}, {"Orders In", type number}, {"Orders Out", type number}, {"Direct Sales Shipped CID", type number}, {"Direct Sales Shipped Felix", type number}, {"Distributor Shipped CID", type number}, {"Distributor Shipped Felix", type number}, {"Interscan Sales", type number}, {"Consulting", type number}, {"Monthly Totals", type number}, {"Average Number of Days From Quote to Sale CID", type number}, {"Average Number of Days From Quote to Sale Felix", type number}, {"Average Number of Days From Payment to Shipping", type number}}),
    #"Added Custom" = Table.AddColumn(#"Changed Type", "Date", each if [Month] = "January" then 1 else if [Month] = "February" then 2 else if [Month] = "March" then 3 else if [Month] = "April" then 4 else if [Month] = "May" then 5 else if [Month] = "June" then 6 else if [Month] = "July" then 7 else if [Month] = "August" then 8 else if [Month] = "September" then 9 else if [Month] = "October" then 10 else if [Month] = "November" then 11 else if [Month] = "December" then 12 else 0),
    #"Inserted Suffix" = Table.AddColumn(#"Added Custom", "Suffix", each Text.From([Date], "en-US") & "/1", type text),
    #"Changed Type1" = Table.TransformColumnTypes(#"Inserted Suffix",{{"Suffix", type date}}),
    #"Filtered Rows" = Table.SelectRows(#"Changed Type1", each [Month] <> null and [Month] <> "")
in
    #"Filtered Rows"

Monthly Report 2 Query

let
    Source = Excel.Workbook(File.Contents("C:\Users\Thomas\Downloads\Summer-2023-Product-Analyst-Intern-Projects-main\Power BI\Monthly Sales Dashboard\Monthly Sales Report Dashboard.xlsx"), null, true),
    #"Monthly Report 2_Sheet" = Source{[Item="Monthly Report 2",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(#"Monthly Report 2_Sheet", [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Instrument", type text}, {"Month", type text}, {"Total Shipped", Int64.Type}}),
    #"Added Custom" = Table.AddColumn(#"Changed Type", "Date", each if [Month] = "January" then 1 else if [Month] = "February" then 2 else if [Month] = "March" then 3 else if [Month] = "April" then 4 else if [Month] = "May" then 5 else if [Month] = "June" then 6 else if [Month] = "July" then 7 else if [Month] = "August" then 8 else if [Month] = "September" then 9 else if [Month] = "October" then 10 else if [Month] = "November" then 11 else if [Month] = "December" then 12 else 0),
    #"Added Suffix" = Table.TransformColumns(#"Added Custom", {{"Date", each Text.From(_, "en-US") & "/1", type text}}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Added Suffix",{{"Date", type date}})
in
    #"Changed Type1"

Pie Chart Query:

let
    Source = Excel.Workbook(File.Contents("C:\Users\Thomas\Downloads\Summer-2023-Product-Analyst-Intern-Projects-main\Power BI\Monthly Sales Dashboard\Monthly Sales Report Dashboard.xlsx"), null, true),
    #"Monthly Report 1_Sheet" = Source{[Item="Monthly Report 1",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(#"Monthly Report 1_Sheet", [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Month", type text}, {"Orders In", type number}, {"Orders Out", type number}, {"Direct Sales Shipped CID", type number}, {"Direct Sales Shipped Felix", type number}, {"Distributor Shipped CID", type number}, {"Distributor Shipped Felix", type number}, {"Interscan Sales", type number}, {"Consulting", type number}, {"Monthly Totals", type number}, {"Average Number of Days From Quote to Sale CID", type number}, {"Average Number of Days From Quote to Sale Felix", type number}, {"Average Number of Days From Payment to Shipping", type number}}),
    #"Demoted Headers" = Table.DemoteHeaders(#"Changed Type"),
    #"Transposed Table" = Table.Transpose(#"Demoted Headers"),
    #"Promoted Headers1" = Table.PromoteHeaders(#"Transposed Table", [PromoteAllScalars=true]),
    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers1",{{"January", type number}, {"February", type number}, {"March", type number}, {"April", type number}, {"May", type number}, {"June", type number}, {"July", Int64.Type}, {"August", Int64.Type}, {"September", Int64.Type}, {"October", Int64.Type}, {"November", Int64.Type}, {"December", Int64.Type}, {"2023 Year To Date Totals", type number}, {"2022 Year End Totals", type number}})
in
    #"Changed Type1"